### ISSUE TITLE
Eijiro コマンドを実行したとき、ValueError: already destroyed. が発生することがある

### ISSUE THREAD

**Issue by crftwr** [crftwr/clnch#16]
Eijiro コマンドを実行したとき、ValueError: already destroyed. が発生することがある

-------

CraftLaunch version 3.30:
  http://sites.google.com/site/craftware/

Traceback (most recent call last):
  File "c:\project\py3\clnch\clnch_mainwindow.py", line 497, in _onActivate
  File "c:\project\py3\clnch\clnch_mainwindow.py", line 817, in paint
  File "c:\project\py3\clnch\clnch_mainwindow.py", line 383, in _onPaint
  File "..\ckit\ckit_widget.py", line 597, in setPosSize
  File "..\ckit\ckit_widget.py", line 593, in _updatePlanePosSize
  File "..\ckit\ckit_theme.py", line 212, in setPosSize
ValueError: already destroyed.

**Comment by crftwr** [comment]
最近起きてない。
